Add app home
JustinHsie/eats pull request #11
Opened 2021-01-10 03:59 UTC by JustinHsie

Created app homepage with react-admin, the link is in the wiki

It took me awhile to learn how the framework works - is this too much framework? ie, should I be building more components by hand?

I followed their tutorial to get set up and it included API calls to jsonPlaceholder. Those became the automatically generated User and Posts links, we can customize with our actual API calls later

I added the custom navigation links as well (Home, Search, New List, New Place)

2021-01-10 17:51 UTC, swissarmybox commented
See my reply on the issue.

2021-01-12 16:15 UTC, swissarmybox commented
@JustinHsie Looks like this, is this correct?
<img width="1278" alt="Screen Shot 2021-01-12 at 11 14 59 AM" src="https://user-images.githubusercontent.com/7025139/104341162-77cbc480-54c7-11eb-9d06-afacec64aab4.png">

2021-01-12 18:55 UTC, JustinHsie commented
Yeah! I know it doesn't look great, but is this ok for now? It has the main menu and the user's list of lists. Things might change as I go along, but is there anything else I should add?
And the later pull requests should have links to the other pages, and the heroku site should have the most updated version

2021-01-12 20:39 UTC, swissarmybox requested changes
> Yeah! I know it doesn't look great, but is this ok for now? Yesterday I left some comments on the 'issues' as a summary of my thoughts. Things might change as I go along, but is there anything else I should add?
> And the later pull requests should have links to the other pages, and the heroku site should have the most updated version

Alright once you address my change I'll merge it. Don't merge it yet.

2021-01-12 20:39 UTC, Exegetech commented on client/src/components/Lists.js
> +    <div>
Seems like this can safely be removed.

2021-01-12 20:39 UTC, Exegetech commented on client/src/components/Lists.js
> +export default Lists;
export default these days are considered an anti-pattern. It also will break compatibility with Babel/TypeScript later.  Use `export const List` in line 5

2021-01-12 20:39 UTC, Exegetech commented on client/src/components/Menu.js
> +export default Menu;
Same as above

2021-01-12 20:39 UTC, Exegetech commented on client/src/fakeData/lists.js
> +export default lists;
Same as above

2021-01-12 20:39 UTC, Exegetech commented on client/src/styles/App.css
> +.App {
I'm curious what style of naming convention for CSS did you learn? Just want to make sure it is consistent later. I usually use BEM but feel free to use whatever you want, as long as consistent.

2021-01-12 21:14 UTC, JustinHsie commented on client/src/styles/App.css
> +.App {
I'm actually not sure if I explicitly learned a naming convention, but I'll start using BEM now

2021-01-12 21:27 UTC, JustinHsie commented
Ok I think I made the changes you requested? I was a little confused because I saw your comments under Files Changed but it also showed changes I previously made to package.json and App. To clarify, those weren't your requests, right? Just stuff from the last commit?

2021-01-13 01:53 UTC, swissarmybox commented
Yeah this is fine. Now usually if you work in another person/organization repo, this Merge pull request will be blocked before 1 or 2 reviews and passing CI system. But since this is your own repo you can merge it yourself. Pretend that you can't now, so only I can merge it.

When you merge, you have the choice to just merge like that, so any commits that you build in this branch will be merged just like that to master. I don't like that approach because it is not clean. When a developer work in a branch, they usually commit for the sake of saving work, regardless what the actual app state (broken or not) at that commit. Commit needs to be atomic, meaning, if I revert a commit, I need to be able to build the app and the app must work and not broken. Imagine if during release you introduce a bug, and your boss tells you to revert back the commit. You want to revert the commit and not finding the app in a half broken state.

Therefore a better approach before merging to master is to squash these commits in this PR. On the green button below, there is a dropdown, there will be an option that says "Squash" and merge. Choose that, and then you will be prompted to input a description. Make a good description. 

What I usually do, in the title I put the feature or branch name (if you use ticketing system, the ticket number), along with the issue number in parentheses. In the body I describe what changes I made.

For example

```
app-home(#11)

Changes:
- Do x
- Do y
- Do z

Resolves #8
```

2021-01-13 01:54 UTC, merged

2021-01-13 01:55 UTC, swissarmybox commented
I have squashed and merged, now check `master` branch and see the commit history. It looks clean like that, and atomic.

2021-01-13 02:45 UTC, JustinHsie commented
Awesome, that's really valuable to know. Thank you so much for the git lesson! I'll do the cherry-picking for the other branch now